---
version: ~> 1.0
conditions: v1
dist: bionic
# Config file for automatic testing at travis-ci.org

language: python

branches:
  only:
    - master
    - devel
    # https://stackoverflow.com/q/37972029/99834
    - /^(\d+!)?(\d+)(\.\d+)+([\.\-\_])?((a(lpha)?|b(eta)?|c|r(c|ev)?|pre(view)?)\d*)?(\.?(post|dev)\d*)?$/

cache:
  - pip
  - directories:
      - "node_modules"
      - $HOME/.cache
os:
  - linux
before_install:
  - which tox >/dev/null || if [ -z ${VIRTUAL_ENV+x} ]; then python -m pip install --upgrade --user tox tox-pyenv pip; else python -m pip install tox tox-pyenv pip; fi
jobs:
  fast_finish: true
  include:
    - name: lint
      env: TOXENV=lint
      python: "3.7"
    # - name: py35
    #   python: "3.5"
    #   env: TOXENV=py35
    - name: py36
      python: "3.6"
      env: TOXENV=py36
    # - name: py37
    #   python: "3.7"
    #   env: TOXENV=py37
    # - name: py38
    #   python: "3.8"
    #   env: TOXENV=py38
    - name: py27
      python: "2.7"
      env: TOXENV=py27
    # - name: devel
    #   python: "3.7"
    #   env: TOXENV=devel
    - stage: deploy
      name: deploy
      if: tag IS present AND type != cron
      addons: {}
      services: []
      env: TOXENV=upload
script:
  # https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - python -m pip freeze --all
  - python -m tox
  - kill %1

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=1

before_cache:
  - rm -rf $HOME/.cache/pip/log
  # Set up KVM
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm
  - virsh list --all

addons:
  apt:
    packages:
      - bridge-utils
      - libpulse0
      - libvirt-bin
      - libvirt-daemon
      - libvirt-dev
      - python-libvirt
      - python3-libvirt
      - qemu-kvm
      - ubuntu-vm-builder
      - virtinst
