---

- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    molecule_dns_suffix: "molecule.lab"
    molecule_network_name: "molecule-network"
    molecule_ssh_user: molecule
    molecule_scenario_name: "{{ lookup('env', 'MOLECULE_SCENARIO_NAME') }}"
    user_home_directory: "{{ lookup('env', 'HOME') }}"
    libvirt_default_image_path: "{{ user_home_directory}}/.local/molecule-libvirt-temp/{{ molecule_scenario_name }}/vms"
    libvirt_uri: "qemu:///system"
    libvirt_vm_arch: x86_64
    temp_folder: "/tmp"

    ssh_port: 22
    mac: "52:54:00:37:13:"  # first 5 digits
    molecule_private_key_path: "/tmp/id_rsa"

  tasks:

    - name: Get list of all instances
      virt:
        command: list_vms
        uri: "{{ libvirt_uri }}"
      register: instance_list

    - name: Check if molecule instance(s) is/are running
      virt:
        command: status
        name: "{{ item.name }}"
        uri: "{{ libvirt_uri }}"
      register: instance_status
      with_items: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.name in instance_list.list_vms

    - name: Stop molecule instance(s)
      virt:
        name: "{{ item.name }}"
        command: shutdown
        uri: "{{ libvirt_uri | default(omit) }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      when: (item.name in instance_list.list_vms) and
            (instance_status.results |
            json_query(jmesquery)) == 'running'
      vars:
        jmesquery: "[?item.name=='{{ item.name }}'].status | [0]"

    - name: Destroy and undefine molecule instance(s)
      virt:
        name: "{{ item.name }}"
        command: undefine
        uri: "{{ libvirt_uri | default(omit) }}"
      with_items: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.name in instance_list.list_vms

    - name: Get libvirt vnet list
      virt_net:
        command: list_nets
        uri: "{{ libvirt_uri | default(omit) }}"
      register: net_list

    - name: Stop molecule network
      virt_net:
        command: stop
        name: "{{ molecule_network_name }}"
        uri: "{{ libvirt_uri | default(omit) }}"
      when: molecule_network_name in net_list.list_nets

    - name: Undefine molecule network
      virt_net:
        command: undefine
        name: "{{ molecule_network_name }}"
        uri: "{{ libvirt_uri | default(omit) }}"
      when: molecule_network_name in net_list.list_nets

    - name: Remove vm image(s)
      file:
        path: "{{ libvirt_default_image_path }}/{{ item.name }}.qcow2"
        state: absent
      with_items: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Remove cloud-init iso image(s)
      file:
        path: "{{ libvirt_default_image_path }}/{{ item.name }}-cloud-init.iso"
        state: absent
      with_items: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Remove folder molecule vms folder
      file:
        path: "{{ user_home_directory}}/.local/molecule-libvirt-temp"
        state: absent
